### ISSUE TITLE
Failed to activate the html-include-resource package

### ISSUE THREAD

**Issue by shuyg** [urecio/html-include-resource#1]
[Enter steps to reproduce below:]

1. Installed package
2. Created almost empty html file.
3. Right-click with mouse on image.
4. Selected "Include resource" from menu.

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [html-include-resource](https://github.com/urecio/html-include-resource) package, v1.2.0

### Stack Trace

Failed to activate the html-include-resource package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (C:\Users\XXXXX\.atom\packages\html-include-resource\lib\html-include-resource.coffee:7:23)
  at Package.module.exports.Package.activateNow (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\XXXXXX\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -7:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:59.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -5:57.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:56.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:56.1.0 core:select-right (atom-text-editor.editor.is-focused)
     -4:33.8.0 core:page-down (div.settings-view.pane-item)
  3x -3:55.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:54.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:34.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoclose-html"
    ]
  }
}
```

### Installed Packages

```coffee
# User
html-entities, v0.4.0
html-include-resource, v1.2.0

# Dev
No dev packages
```

**Comment by urecio** [comment]
Hi, thanks for your report. It should be fine now

**Comment by shuyg** [comment]
Hello Unai,

Thanks, it's working indeed.

Sjoerd

On 3-7-2015 14:53, Unai Recio wrote:
>
> Hi, thanks for your report. It should be fine now
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/urecio/html-include-resource/issues/1#issuecomment-118339645>.
>


-- 

	
	Roadside BV <http://www.roadside.nl> 		Klapbrugweg 6
1332AK Almere 		T 036 521 67 31
F 036 521 67 32 		www.roadside.nl <http://www.roadside.nl>
info@roadside.nl <mailto:info@roadside.nl>
