### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by newelement** [urecio/html-include-resource#3]
This has stopped working in Atom 1.16

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [html-include-resource](https://github.com/urecio/html-include-resource) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined

```
At /Users/donjones/.atom/packages/html-include-resource/lib/html-include-resource.coffee:16

TypeError: Cannot read property 'querySelectorAll' of undefined
    at Object.include (/packages/html-include-resource/lib/html-include-resource.coffee:16:39)
    at /packages/html-include-resource/lib/html-include-resource.coffee:8:78)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:46 core:move-left (input.hidden-input)
     -1:44.5.0 core:move-right (input.hidden-input)
     -1:44 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:44 docblockr:parse-enter (input.hidden-input)
     -1:44 editor:newline (input.hidden-input)
     -1:43.3.0 core:move-up (input.hidden-input)
 12x -1:43 core:move-right (input.hidden-input)
     -1:41.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:41.2.0 docblockr:parse-enter (input.hidden-input)
     -1:41.2.0 editor:newline (input.hidden-input)
  5x -1:38.8.0 core:move-left (input.hidden-input)
  5x -1:29.7.0 core:backspace (input.hidden-input)
     -0:16.5.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:16.5.0 docblockr:parse-enter (input.hidden-input)
     -0:16.5.0 editor:newline (input.hidden-input)
     -0:04.5.0 html-include-resource:include (span.name.icon.image-icon.medium-orange)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-typescript 10.1.15 
atom-wordpress 0.3.0 
autocomplete-html-entities 0.1.0 
autocomplete-php 0.3.7 
chary-tree-view 0.2.3 
color-picker 2.2.5 
docblockr 0.9.1 
docker 0.7.0 
emmet 2.4.3 
file-icons 2.0.17 
flex-tool-bar 0.12.0 
git-control 0.8.2 
git-time-machine 1.5.6 
html-include-resource 1.3.0 
imagemin 1.5.1 
language-babel 2.56.2 
language-docker 1.1.7 
less-than-slash 0.16.0 
linter 1.11.23 
linter-csslint 1.3.4 
linter-htmlhint 1.3.2 
linter-jscs 4.1.2 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-php 1.3.1 
linter-scss-lint 3.1.0 
linter-tidy 2.3.0 
minimap 4.26.8 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-linter 1.6.0 
pigments 0.39.0 
project-viewer 1.0.9 
react 0.16.2 
Remote-FTP 0.10.7 
svg-preview 0.11.0 
sync-settings 0.8.1 
terminal-plus 0.14.5 
tool-bar 1.1.0 
```

**Comment by urecio** [comment]
Thanks for letting me know. Although 1.16 is still in Beta stage.

**Comment by OxLeon** [comment]
Same issue here! :(
